# Generated by Django 5.1.7 on 2025-03-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
