# Generated by Django 5.1.7 on 2025-03-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='job',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('M', 'Manager'), ('E', 'Employee'), ('S', 'Student'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
