# Generated by Django 5.1.7 on 2025-03-12 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='down_vote',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='poll',
            name='up_vote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
