# Generated by Django 5.1.7 on 2025-03-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_poll_down_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='down_vote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
