# Generated by Django 5.1.7 on 2025-03-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_poll_downvoted_by_poll_upvoted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
