# Generated by Django 5.0.2 on 2025-03-17 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_comment_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='body',
        ),
    ]
